openapi: 3.0.0
info:
  title: Park API
  version: 1.0.0
paths:
  /hello:
    get:
      tags:
        - hello
      summary: Returns a greeting
      operationId: sayHello
      x-eov-operation-handler: hello
      responses:
        '200':
          description: A successful response

